apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    service: postgres
spec:
  ports:
  - name: tcp-postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: names
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: v1
  template:
    metadata:
      labels:
        app: postgres
        version: v1
    spec:
      serviceAccountName: postgres
      containers:
      - image: postgres:13
        imagePullPolicy: "IfNotPresent"
        envFrom:
          - configMapRef:
              name: postgres-config
        name: postgres
        ports:
        - containerPort: 5432
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - customer
                - person
                - name
            topologyKey: "kubernetes.io/hostname"